// STUB(R.Chen): Forge LoaderState — compile shim.
package net.minecraftforge.fml.common;

public enum LoaderState {
    NOINIT, LOADING, CONSTRUCTING, PREINITIALIZATION, INITIALIZATION, POSTINITIALIZATION, AVAILABLE, SERVER_ABOUT_TO_START, SERVER_STARTING, SERVER_STARTED, SERVER_STOPPING, SERVER_STOPPED, ERRORED
}
